#@ load("@ytt:data", "data")

#! These secrets should not be rotated:
#! "credhub-encryption-key"

#@ if data.values.rotate_quark_secrets:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rotate
  labels:
    quarks.cloudfoundry.org/secret-rotation: "true"
data:
  secrets: '["concourse-admin-user-credentials",
"concourse-postgresql-password",
"credhub-admin-client-credentials",
"credhub-client-user-credentials",
"credhub-keystore-key",
"credhub-postgresql-password",
"credhub-templated-admin-client-credentials",
"credhub-truststore-key",
"credhub-config",
"credhub.ca",
"host-key",
"jwt-keys",
"local-user",
"session-signing-key",
"templated-concourse-web",
"templated-concourse-worker",
"uaa-admin-client-credentials-quarkssecret",
"uaa-encryption-key",
"uaa-encryption-keys",
"uaa-jwt-policy-signing-keys",
"uaa-postgresql-password",
"uaa-saml-keys-file",
"uaa-templated-admin-client-credentials",
"uaa-templated-concourse-user-credentials",
"uaa-templated-database-credentials",
"uaa.saml-keys",
"uaa.saml-keys-ca",
"worker-key"]'
#@ end
